# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Get version from commits count
      id: versioning
      run: |
        VERSION=$(git rev-list --count HEAD)
        echo "Version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_ENV

    - name: Update version in POM
      run: |
        sed -i "/<artifactId>best-first-guided-modeling<\/artifactId>/!b;n;c<version>1.0.${{ env.version }}</version>" pom.xml


    - name: Show pom.xml
      run: cat pom.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: best-first-guided-modeling-${{ env.version }}.jar
        path: target/best-first-guided-modeling-${{ env.version }}.jar

    - name: Create a GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/best-first-guided-modeling-${{ env.version }}.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
