name: Maven Build and Versioning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Setup Maven
        uses: s4u/maven-settings-action@v2

      - name: Get version from commits count
        id: versioning
        run: |
          VERSION=$(git rev-list --count HEAD)
          echo "Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Update version in POM
        run: |
          sed -i "s/<version>.*<\/version>/<version>1.0.${{ env.version }}<\/version>/" pom.xml


      - name: Clear maven cache
        run: rm -rf ~/.m2/repository

      - name: Build project with Maven
        run: mvn clean install -U


      - name: Create JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: best-first-guided-modeling-${{ env.version }}.jar
          path: target/best-first-guided-modeling-${{ env.version }}.jar

      - name: Create a GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/best-first-guided-modeling-${{ env.version }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
